### ISSUE TITLE
coco-hand and coco basic training command difference

### ISSUE THREAD

**Issue by youngjae-avikus** [uyzhang/yolov5_prune#1]
https://github.com/uyzhang/yolov5_prune#steps

In basic training number 2, coco-hand is based on pre-trained weight, but it is not coco, which one is correct?
As far as I know, it is related to the `botleneck ignore` problem for sparsity training, should we proceed with the existing pretrained weight before sparsity training?

**Comment by uyzhang** [comment]
It's been modified. The basic training of data sets does not need to load pre-training weights. thx!

**Comment by youngjae-avikus** [comment]
@uyzhang is there any reason why you did it with adamw?  There is not much difference from sgd to calc sparsity, but if there is another reason, can I know?

**Comment by uyzhang** [comment]
I tried sparse training with SGD, but the effect was not good. AdamW works well, so I end up using AdamW.
