### ISSUE TITLE
question about sparsity training gpu memory

### ISSUE THREAD

**Issue by youngjae-avikus** [uyzhang/yolov5_prune#2]
Hello, after basic training, I tried to run it in the same conditional environment as the sparsity training. But out of memory occurred. I think the only addition is the l1 regularization of bn param (scaling factor, bias), is this a lot of memory when subgradient calculation of that param is done? Or is there another reason? It takes about 2 hour per epoch (Of course, the image size was big, so it took about 40 minutes for basic training) thank you for contrib

**Comment by uyzhang** [comment]
I have tried sparse training at the resolution of 640x640, and the speed has basically not changed much.

**Comment by youngjae-avikus** [comment]
I don't think there was a big problem when I turned the coco-hand example, so would the hardware issue be big?
